// Simple model for game data
const games = [
  {
    id: "1",
    name: "Season Opener vs State University",
    date: "October 15, 2023",
    league: "University League",
    season: "2023-2024",
    gameDate: new Date(2023, 9, 15),
    venue: "University Gym",
    gameNumber: "Game #1",
    gameType: "Regular Season",
    division: "Men's Division",
    opponent: "State University",
  },
  {
    id: "2",
    name: "Away Game vs City College",
    date: "October 22, 2023",
    league: "University League",
    season: "2023-2024",
    gameDate: new Date(2023, 9, 22),
    venue: "City College Arena",
    gameNumber: "Game #2",
    gameType: "Regular Season",
    division: "Men's Division",
    opponent: "City College",
  },
  {
    id: "3",
    name: "Home Game vs Tech Institute",
    date: "October 29, 2023",
    league: "University League",
    season: "2023-2024",
    gameDate: new Date(2023, 9, 29),
    venue: "University Gym",
    gameNumber: "Game #3",
    gameType: "Regular Season",
    division: "Men's Division",
    opponent: "Tech Institute",
  },
  {
    id: "4",
    name: "Tournament First Round",
    date: "November 5, 2023",
    league: "University League",
    season: "2023-2024",
    gameDate: new Date(2023, 10, 5),
    venue: "Regional Sports Complex",
    gameNumber: "Game #4",
    gameType: "Tournament",
    division: "Men's Division",
    opponent: "Metro University",
  },
  {
    id: "5",
    name: "Tournament Semi-Finals",
    date: "November 12, 2023",
    league: "University League",
    season: "2023-2024",
    gameDate: new Date(2023, 10, 12),
    venue: "Regional Sports Complex",
    gameNumber: "Game #5",
    gameType: "Tournament",
    division: "Men's Division",
    opponent: "Capital College",
  },
  {
    id: "6",
    name: "Tournament Finals",
    date: "November 19, 2023",
    league: "University League",
    season: "2023-2024",
    gameDate: new Date(2023, 10, 19),
    venue: "National Arena",
    gameNumber: "Game #6",
    gameType: "Tournament",
    division: "Men's Division",
    opponent: "State University",
  },
];

export default {
  getAllGames: () => games,
  getGameById: (id) => games.find((game) => game.id === id),
  addGame: (game) => {
    const newGame = { id: (games.length + 1).toString(), ...game };
    games.push(newGame);
    return newGame;
  },
};
